### ISSUE TITLE
Mongo Cloud Atlas DB

### ISSUE THREAD

**Issue by mindamp** [Requarks/wiki-v1#170]
Wiki-v1

Fresh install, trying to use Mongo Atlas URI string:

`MongoError: The field 'background' is not valid for an _id index specification. Specification: { v: 2, ns: "iocraft.bruteforces", key: { _id: 1 }, $
    at Function.MongoError.create (/storage/website/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
    at /storage/website/node_modules/mongoose/node_modules/mongodb/lib/db.js:1093:80
    at /storage/website/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Unhandled rejection MongoError: The field 'background' is not valid for an _id index specification. Specification: { v: 2, ns: "iocraft.bruteforces$
    at Function.MongoError.create (/storage/website/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
    at /storage/website/node_modules/mongoose/node_modules/mongodb/lib/db.js:1093:80
    at /storage/website/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at process._tickCallback (internal/process/next_tick.js:61:11)`

'background' not supported in _id field for Mongo 3.4 apparently. Any solution? Does Wiki-v2 use an updated Mongo driver?

**Comment by mindamp** [comment]
Didn't realize I could build an older cluster instead of 4.0 on Mongo Atlas. Resolved.
