### ISSUE TITLE
Uploading some JPEG files breaks git sync

### ISSUE THREAD

**Issue by fpagnoux** [Requarks/wiki-v1#180]
### Actual behavior

When I update a specific JPEG file like this one[https://drive.google.com/file/d/1PQEfej2oB8XnLJrKBV_8lBFSf5dXhYhR/view?usp=sharing], the following happens:

- An error message appears on the website: "Unable to fetch updated listing." (as in #47) 
- I get this error in the logs:
```
Unhandled rejection TypeError: Corrupt JPG, exceeded buffer limits
    at validateBuffer (/webapps/bod-wiki/node_modules/image-size/lib/types/jpg.js:23:11)
    at Object.calculate (/webapps/bod-wiki/node_modules/image-size/lib/types/jpg.js:42:5)
    at lookup (/webapps/bod-wiki/node_modules/image-size/lib/index.js:26:31)
    at /webapps/bod-wiki/node_modules/image-size/lib/index.js:93:22
    at /webapps/bod-wiki/node_modules/image-size/lib/index.js:50:9
    at /webapps/bod-wiki/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
```
- If I restart my instance, the git sync stops happening (my main issue), probably because the agent stops after encountering the error above.

The root error probably comes from [this issue](https://github.com/image-size/image-size/issues/37) which is not related to Wiki.js. But the fact that uploading an image breaks the git sync is problematic IMHO.  

### Expected behavior

That the issue processing an image doesn't impact git synchronization

### Steps to reproduce the behavior

See details above

**Comment by colo13c** [comment]
Hi,
how do you fix it? I have the same issue and I dont know how to resolve it. Thanks anyway.

**Comment by fpagnoux** [comment]
I think I identified the problematic JPG, and re-uploaded them.
That fixed the git sync for a while but then it broke again, not sure why.
To avoid data losses I ended up adding a cron job that runs a `git push` every hour on the server. 
Sad to say but the git sync on wiki.js v1 is really not reliable. Not sure if things got better in the new version.
