### ISSUE TITLE
Wikijs is not sync wit gitlab

### ISSUE THREAD

**Issue by phamtai97** [Requarks/wiki-v1#183]
I config file config.yaml like that:
```bash
git:
  url: 'git@gitlab.zalopay.vn:taiptht_zlp/zas_wiki.git'
  branch: master
  auth:
    type: ssh
    privateKey: /home/phamtai97/.ssh/id_rsa
    sslVerify: false
```
And I check:

```sh
$ node server
```
Result:

```sh
➜  wikijs node server      
2019-03-10T13:59:59.259Z - info: [SERVER] Wiki.js is initializing...
2019-03-10T13:59:59.354Z - info: [SERVER] Checking data directories...
2019-03-10T13:59:59.355Z - info: [SERVER] Data and Repository directories are OK.
2019-03-10T13:59:59.532Z - info: [SERVER] Checking Git repository...
2019-03-10T14:00:00.233Z - info: [SERVER] Starting HTTP/WS server on port 9999...
2019-03-10T14:00:00.249Z - error: [SERVER] Port 9999 is already in use!
➜  wikijs 2019-03-10T14:00:00.378Z - info: [AGENT] Background Agent is initializing...
2019-03-10T14:00:00.780Z - info: [AGENT] Checking Git repository...
2019-03-10T14:00:01.189Z - warn: [AGENT] Lost connection to main server. Exiting...
/home/phamtai97/taiptht/wikijs/server/agent.js:222
  job.stop()
      ^

TypeError: Cannot read property 'stop' of undefined
    at process.on (/home/phamtai97/taiptht/wikijs/server/agent.js:222:7)
    at emitNone (events.js:106:13)
    at process.emit (events.js:208:7)
    at finish (internal/child_process.js:747:14)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```
I have waited more than 5 minutes but the data is still not sync. 
Can you explain help me.

**Comment by NGPixel** [comment]
`2019-03-10T14:00:00.249Z - error: [SERVER] Port 9999 is already in use!`

**Comment by phamtai97** [comment]
No programs run on port 9999. I only run port 9999 for wikijs program. 
I don't use nginx so i config url: localhost:9999 and port 9999

**Comment by NGPixel** [comment]
The error says otherwise. The port is not available and causes the app to exit.

**Comment by phamtai97** [comment]
Thanks, I will try other way.
