### ISSUE TITLE
Agent does not run every five minutes

### ISSUE THREAD

**Issue by robp2175** [Requarks/wiki-v1#186]
### Actual behavior
When agent runs I get this error. (I had to turn off mathjax or I received another error as well)

```
OperationalError: Entry readme does not exist!
    at fs.statAsync.then.catch (/var/wiki/server/libs/entries.js:164:13)
    at tryCatcher (/var/wiki/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/wiki/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/wiki/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/wiki/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/wiki/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/var/wiki/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/wiki/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/wiki/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
2019-03-29T17:00:59.220Z - error: [AGENT]  TypeError: Cannot read property 'title' of undefined
    at self.fetchOriginal.catch.then.catch.then (/var/wiki/server/libs/entries.js:264:29)
    at tryCatcher (/var/wiki/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/wiki/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/wiki/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/wiki/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/wiki/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/var/wiki/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._settlePromise (/var/wiki/node_modules/bluebird/js/release/promise.js:582:21)
    at Promise._settlePromise0 (/var/wiki/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/wiki/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/var/wiki/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/var/wiki/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/var/wiki/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/var/wiki/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/wiki/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/wiki/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/var/wiki/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/var/wiki/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/var/wiki/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/var/wiki/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/wiki/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/wiki/node_modules/bluebird/js/release/promise.js:689:18)
2019-03-29T17:00:59.742Z - info: [AGENT] All jobs completed successfully! Going to sleep for now.
```
### Expected behavior
For the agent to run every five mintes without error

### Steps to reproduce the behavior
node server

**Comment by robp2175** [comment]
Turns out my readme file was empty and there was some corrupted file in there. Just had to put something in ithe readme and deleted the other file.
